name: CI/CD demo
on:
    push:
        branches: [ main, dev]
    pull_request:
        branches: [ main, dev]
jobs:
    test:
        name: Run Tests
        runs-on: self-hosted
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Verify Python version
              run: |
                python3 --version
                Get-Command python3
            # - name: Install dependencies
            #   run: |
            #     python -m pip install -r requirements.txt
            - name: Run tests
              run: |
                python -m pytest test_app.py -v
    build:
        name: Build Docker Image
        runs-on: self-hosted
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Build Docker Image
              run: docker build -t ci-cd-demo:latest .
    deploy:
        name: Deploy to localhost
        runs-on: self-hosted
        needs: build
        if: github.ref == 'refs/heads/main'

        steps:
            - name: stop old container
              run: |
                try { docker stop python-app } catch { }
                try { docker rm python-app } catch { }
            - name: start new container
              run: |
                docker run -d --name python-app -p 5001:5001 --restart unless-stopped ci-cd-demo:latest
            - name: check deployment
              run: |
                Start-Sleep 10
                curl -X GET http://localhost:5001/health || exit 1
                echo "Deployment successful"
            - name: show running containers
              run: docker ps | Select-String python-app